---
title: "Week7b_setup_api"
author: "Roshan"
date: "2023-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Installing Packages
```{r}

options(repos = "https://cran.r-project.org")

```

# Loading Libraries
```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(data.table)
library(ggrepel)
library(tidyverse)
library(ggsn)
library(ggmap)
library(here)
library(ggspatial)





register_google(key = "AIzaSyAOb8vDcmuEg-IVplAe73XJvBjcsyqx1a8", write = TRUE)
```
```{r}
ChemData<-read_csv(here("Week_07","Data","chemicaldata_maunalua.csv"))
Oahu<-get_map("Oahu")

ggmap(Oahu)

#Make a data frame of lon and lat coordinates
WP<-data.frame(lon = -157.7621, lat = 21.27427) # coordinates for Wailupe
# Get base layer
Map1<-get_map(WP)
# plot it
ggmap(Map1)

Map1<-get_map(WP,zoom = 17, maptype = "satellite")
ggmap(Map1)+
geom_point(data = ChemData, 
             aes(x = Long, y = Lat, color = Salinity), 
             size = 4)+
  scale_color_viridis_c()+
  scalebar( x.min = -157.766, x.max = -157.758,
           y.min = 21.2715, y.max = 21.2785,
            dist = 250, dist_unit = "m", model = "WGS84", 
            transform = TRUE, st.color = "white",
            box.fill = c("yellow", "white"))


```




