---
title: "Week7a_map_homework"
author: "Roshan"
date: "2023-03-07"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Loading Libraries
```{r}

library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
```

# Loading *World* & *UK Cat* Data
```{r}
##load data
world<-map_data("world")
tuesdata <- tidytuesdayR::tt_load('2023-01-31')
cats_uk <- tuesdata$cats_uk
```

# Loading coordinates & map
```{r}
world<-map_data("world")
UK<-map_data("world", region = "UK")
view(UK)
view(cats_uk)
ggplot()+
  geom_polygon(data = UK, aes(x = long, y = lat, group = group,
                                 fill = subregion),
                                 color = "blue")+
  theme_dark()+
  theme(panel.background = element_rect(fill = "lightblue"))+
            
  geom_point(data = cats_uk,
             aes(x = location_long,
                  y = location_lat))+
  labs(title = "UK Cat data for South East")
```


# Saving Work
```{r}
ggsave(here("Week_07", "Output", "Week_7_homework_UKcatsMaps.png"))
```



